### PR TITLE
typo in FileOperations.cpp

### PR DESCRIPTION
**Pull request by niemarcin**

### CODE REVIEW

**Review by ziobron — COMMENTED** [review]
It was done on purpose, because I had a file example.cpp. Better name is "thisFileDoesNotExist.cpp" ;)

**Comment by niemarcin** [comment]
@ziobron  Do you want me to change it or just close the PR without changes? :)

**Comment by ziobron** [comment]
@niemarcin change it please :)

**Comment by niemarcin** [comment]
@ziobron done  :)

**Review by ziobron — APPROVED** [review]

**Pull request merged**
